name: AdminToggle
main: com.github.blir.admintoggle.AdminToggle
version: 3.0.0
author: Blir
softdepend: [Vault]
commands:
  adminswitch:
    description: Toggles admin mode.
    usage: §c/<command>
    permission: admintoggle.adminswitch
    permission-message: §cYou don't have permission to use that command.
    aliases: [asdf, adswitch]
  newsnapshot:
    description: Creates a new snapshot save.
    usage: §c/<command> <snapshot name>
    permission: admintoggle.newsnapshot
    permission-message: §cYou don't have permission to use that command.
    aliases: newsnap
  overwritesnapshot:
    description: Overwrites an existing save.
    usage: §c/<command> <snapshot name>
    permission: admintoggle.overwritesnapshot
    permission-message: §cYou don't have permission to use that command.
    aliases: [osnap, overwritesnap]
  loadsnapshot:
    description: Loads the specified save.
    usage: §c/<command> <snapshot name>
    permission: admintoggle.loadsnapshot
    permission-message: §cYou don't have permission to use that command.
    aliases: [loadsnap, lsnap]
  listsnapshots:
    description: Lists your current snapshots.
    usage: §c/<command>
    permission: admintoggle.listsnapshots
    permission-message: §cYou don't have permission to use that command.
    aliases: [listsnaps, mysnapshots, mysnaps]
  allsnapshots:
    description: Lists all snapshots.
    usage: §c/<command>
    permission: admintoggle.allsnapshots
    permission-message: §cYou don't have permission to use that command
    aliases: [allsnaps]
  deletesnapshot:
    description: Deletes the specified snapshot.
    usage: §c/<command> <snapshot name>
    permission: admintoggle.deletesnapshot
    permission-message: §cYou don't have permission to use that command.
    aliases: [delsnap, dsnap, deletesnap, removesnapshot, removesnap, rmsnap]
  savesnapshots:
    description: Saves all snapshots to file.
    usage: §c/<command>
    permission: admintoggle.savesnapshots
    permission-message: §cYou don't have permission to use that command.
    aliases: [savesnaps]
  admincheck:
    description: Returns whether admin mode is currently enabled.
    usage: §c/<command>
    permission: admintoggle.admincheck
    permission-message: §cYou don't have permission to use that command.
    aliases: [adcheck, adc]
  undosnapshot:
    description: Reverts back to your previous snapshot.
    usage: §c/<command>
    permission: admintoggle.undosnapshot
    permission-message: §cYou don't have permission to use that command.
    aliases: [undosnap, undosnaps, usnap]
  deletemysnapshots:
    description: Deletes all of your snapshots.
    usage: §c/<command> CONFIRM
    permission: admintoggle.deletemysnapshots
    permission-message: §cYou don't have permission to use that command.
  loadothersnapshot:
    description: Loads the specified snapshot from the specified user.
    usage: §c/<command> <player name> <snapshot name>
    permission: admintoggle.loadothersnapshot
    permission-message: §cYou don't have permission to use that command.
    aliases: [loadothersnap, losnap]
  createworldgroup:
    description: Creates a new world group with the given name.
    usage: §c/<command> <name> [first world] [second world] [and so on...]
    permission: admintoggle.createworldgroup
    permission-message: §cYou don't have permission to use that command.
    aliases: []
  addtoworldgroup:
    description: Adds the specified world(s) to this world group.
    usage: §c/<command> <first world> [second world] [and so on...]
    permission: admintoggle.addtoworldgroup
    permission-message: §cYou don't have permission to use that command.
    aliases: []
  removefromworldgroup:
    description: Removes the specified world(s) from this world group.
    usage: §c/<command> <first world> [second world] [and so on...]
    permission: admintoggle.removefromworldgroup
    permission-message: §cYou don't have permission to use that command.
    aliases: [deletefromworldgroup]
  deleteworldgroup:
    description: Deletes the specified world group.
    usage: §c/<command> <world group name>
    permission: admintoggle.deleteworldgroup
    permission-message: §cYou don't have permission to use that command.
    aliases: []
  listworldgroups:
    description: Lists all world groups and the worlds belonging to them.
    usage: §c/<command>
    permission: admintoggle.listworldgroups
    permission-message: §cYou don't have permission to use that command.
    aliases: []
  movesnapshot:
    description: Moves the specified snapshot to the specified world.
    usage: §c/<command> <snapshot name> <world name> <user of the snapshot if from console> <world group of the snapshot if from console>
    permission: admintoggle.movesnapshot
    permission-message: §cYou don't have permission to use that command.
    aliases: movesnap
  snapshottype:
    description: Changes the visibility of the specified snapshot.
    usage: §c/<command> <snapshot name> <global|private|grouped>
    permission: admintoggle.snapshottype
    permission-message: §cYou don't have permission to use that command.
    aliases: snaptype
  admintoggle:
    description: Returns help for this plugin
    usage: §c"/<command> help <page>" Or "/<command> version" for version info
    permission: admintoggle.admintoggle
    permission-message: §cYou don't have permission to use that command.
permissions:
  admintoggle.*:
    children:
      admintoggle.adminswitch: true
      admintoggle.newsnapshot: true
      admintoggle.loadsnapshot: true
      admintoggle.listsnapshots: true
      admintoggle.deletesnapshot: true
      admintoggle.savesnapshots: true
      admintoggle.admincheck: true
      admintoggle.undosnapshot: true
      admintoggle.deletemysnapshots: true
      admintoggle.overwritesnapshot: true
      admintoggle.allsnapshots: true
      admintoggle.loadothersnapshot: true
      admintoggle.createworldgroup: true
      admintoggle.addtoworldgroup: true
      admintoggle.removefromworldgroup: true
      admintoggle.deleteworldgroup: true
      admintoggle.listworldgroups: true
      admintoggle.deletesnapshot: true
      admintoggle.movesnapshot: true
      admintoggle.snapshottype: true
      admintoggle.admintoggle: true
  admintoggle.basic:
    children:
      admintoggle.adminswitch: true
      admintoggle.newsnapshot: true
      admintoggle.loadsnapshot: true
      admintoggle.listsnapshots: true
      admintoggle.deletesnapshot: true
      admintoggle.admincheck: true
      admintoggle.undosnapshot: true
      admintoggle.deletemysnapshots: true
      admintoggle.overwritesnapshot: true
      admintoggle.snapshottype: true
  admintoggle.adminswitch:
    description: Allows use of the /adminswitch command.
  admintoggle.newsnapshot:
    description: Allows use of the /newsnapshot command.
  admintoggle.loadsnapshot:
    description: Allows use of the /loadsnapshot command.
  admintoggle.listsnapshots:
    description: Allows use of the /listsnapshots command.
  admintoggle.deletesnapshot:
    description: Allows use of the /deletesnapshot command.
  admintoggle.savesnapshots:
    description: Allows use of the /savesnapshots command.
  admintoggle.admincheck:
    description: Allows use of the /admincheck command.
  admintoggle.undosnapshot:
    description: Allows use of the /undosnapshot command.
  admintoggle.deletemysnapshots:
    description: Allows use of the /deleteallsnapshots command.
  admintoggle.overwritesnapshot:
    description: Allows use of the /overwritesnapshot command.
  admintoggle.allsnapshots:
    description: Allows use of the /listallsnapshots command.
  admintoggle.loadothersnapshot:
    description: Allows use of the /loadothersnapshot command.
  admintoggle.createworldgroup:
    description: Allows use of the /createworldgroup command.
  admintoggle.addtoworldgroup:
    description: Allows use of the /addtoworldgroup command.
  admintoggle.removefromworldgroup:
    description: Allows use of the /removefromworldgroup command.
  admintoggle.listworldgroups:
    description: Allows use of the /listworldgroups command.
  admintoggle.deleteworldgroup:
    description: Allows use of the /deleteworldgroup command.
  admintoggle.movesnapshot:
    description: Allows use of the /movesnapshot command.
  admintoggle.snapshottype:
    description: Allows use of the /snapshottype command.
  admintoggle.admintoggle:
    description: Allows use of the /admintoggle command.