name: AdminToggle
main: com.minepop.servegame.admintoggle.Admin
version: 1.0.2
author: Blir
softdepend: [Vault]
commands:
  adminswitch:
    description: Toggles admin mode.
    usage: /<command>
    permission: admintoggle.adminswitch
    permission-message: You don't have permission to use that command.
    aliases: [asdf, adswitch]
  newsnapshot:
    description: Creates a new save.
    usage: /<command> <snapshot name>
    permission: admintoggle.newsnapshot
    permission-message: You don't have permission to use that command.
    aliases: newsnap
  overwritesnapshot:
    description: Overwrites an existing save.
    usage: /<command> <snapshot name>
    permission: admintoggle.overwritesnapshot
    permission-message: You don't have permissions to use that command.
    aliases: [osnap, overwritesnap]
  loadsnapshot:
    description: Loads the specified save.
    usage: /<command> <snapshot name>
    permission: admintoggle.loadsnapshot
    permission-message: You don't have permission to use that command.
    aliases: [loadsnap, lsnap]
  mysnapshots:
    description: Lists your current snapshots.
    usage: /<command>
    permission: admintoggle.mysnapshots
    permission-message: You don't have permission to use that command.
    aliases: [mysnaps, mysnap]
  allsnapshots:
    description: Lists all snapshots.
    usage: /<command>
    permission: admintoggle.allsnapshots
    permission-message: You don't have permission to use that command
    aliases: [allsnaps, allsnap]
  deletesnapshot:
    description: Deletes the specified save.
    usage: /<command> <snapshot name>
    permission: admintoggle.deletesnapshot
    permission-message: You don't have permission to use that command.
    aliases: [delsnap, dsnap, deletesnap, removesnapshot, removesnap, rmsnap]
  savesnapshots:
    description: Saves the snapshots.
    usage: /<command>
    permission: admintoggle.savesnapshots
    permission-message: You don't have permission to use that command.
    aliases: [savesnaps, savesnap]
  admincheck:
    description: Returns if admin mode is currently enabled.
    usage: /<command>
    permission: admintoggle.admincheck
    permission-message: You don't have permission to use that command.
    aliases: [adcheck, adc]
  undosnapshot:
    description: Reverts back to your previous snapshot.
    usage: /<command>
    permission: admintoggle.undosnapshot
    permission-message: You don't have permission to use that command.
    aliases: [undosnap, undosnaps, usnaps, usnap]
  deletemysnapshots:
    description: Deletes all snapshots.
    usage: /<command> CONFIRM
    permission: admintoggle.deletemysnapshots
    permission-message: You don't have permission to use that command.
  loadothersnapshot:
    description: Loads the specified snapshot from the specified user.
    usage: /<command> <player name> <snapshot name>
    permission: admintoggle.loadothersnapshot
    permission-message: You don't have permission to use that command.
    aliases: [loadothersnap, losnap]
permissions:
  admintoggle.*:
    children:
      admintoggle.adminswitch: true
      admintoggle.newsnapshot: true
      admintoggle.loadsnapshot: true
      admintoggle.mysnapshots: true
      admintoggle.deletesnapshot: true
      admintoggle.savesnapshots: true
      admintoggle.admincheck: true
      admintoggle.undosnapshot: true
      admintoggle.deletemysnapshots: true
      admintoggle.overwritesnapshot: true
      admintoggle.allsnapshots: true
      admintoggle.loadothersnapshot: true
  admintoggle.basic:
    children:
      admintoggle.adminswitch: true
      admintoggle.newsnapshot: true
      admintoggle.loadsnapshot: true
      admintoggle.mysnapshots: true
      admintoggle.deletesnapshot: true
      admintoggle.admincheck: true
      admintoggle.undosnapshot: true
      admintoggle.deletemysnapshots: true
      admintoggle.overwritesnapshot: true
  admintoggle.adminswitch:
    description: Allows use of the /adminswitch command.
  admintoggle.newsnapshot:
    description: Allows use of the /newsnapshot command.
  admintoggle.loadsnapshot:
    description: Allows use of the /loadsnapshot command.
  admintoggle.mysnapshots:
    description: Allows use of the /listsnapshots command.
  admintoggle.deletesnapshot:
    description: Allows use of the /deletesnapshot command.
  admintoggle.savesnapshots:
    description: Allows use of the /savesnapshots command.
  admintoggle.admincheck:
    description: Allows use of the /admincheck command.
  admintoggle.undosnapshot:
    description: Allows use of the /undosnapshot command.
  admintoggle.deletemysnapshots:
    description: Allows use of the /deleteallsnapshots command.
  admintoggle.overwritesnapshot:
    description: Allows use of the /overwritesnapshot command.
  admintoggle.allsnapshots:
    description: Allows use of the /listallsnapshots command.
  admintoggle.loadothersnapshot:
    description: Allows use of the /loadothersnapshot command.