name: AdminToggle
main: com.minepop.servegame.admintoggle.Admin
version: 1.2.3
author: Blir
commands:
  adminswitch:
    description: Toggles admin mode.
    usage: /<command>
    permission: admintoggle.adminswitch
    permission-message: You don't have permission to use that command.
    aliases: [asdf, adswitch, switch]
  newsnapshot:
    description: Creates a new save.
    usage: /<command> [save name]
    permission: admintoggle.newsnapshot
    permission-message: You don't have permission to use that command.
    aliases: snap
  overwritesnapshot:
    description: Overwrites an existing save.
    usage: /<command> [save name]
    permission: amintoggle.overwritesnapshot
    permission-message: You don't have permissions to use that command.
    aliases: osnap
  loadsnapshot:
    description: Loads the specified save.
    usage: /<command> [save name]
    permission: admintoggle.loadsnapshot
    permission-message: You don't have permission to use that command.
    aliases: [loadsnap, lsnap]
  listsnapshots:
    description: Lists your current snapshots.
    usage: /<command>
    permission: admintoggle.listsnapshots
    permission-message: You don't have permission to use that command.
    aliases: [list, listsnaps, lsnaps]
  listallsnapshots:
    description: Lists all snapshots.
    usage: /<command>
    permission: admintoggle.listallsnapshots
    permission-message: You don't have permission to use that command
    aliases: [listall, listallsnaps, lasnaps]
  deletesnapshot:
    description: Deletes the specified save.
    usage: /<command> [save name]
    permission: admintoggle.deletesnapshot
    permission-message: You don't have permission to use that command.
    aliases: [delsnap, dsnap]
  savesnapshots:
    description: Saves the snapshots.
    usage: /<command>
    permission: admintoggle.savesnapshots
    permission-message: You don't have permission to use that command.
    aliases: savesnaps
  admincheck:
    description: Returns if admin mode is currently enabled.
    usage: /<command>
    permission: admintoggle.admincheck
    permission-message: You don't have permission to use that command.
    aliases: adcheck, ad
  undosnapshot:
    description: Reverts back to your previous snapshot.
    usage: /<command>
    permission: admintoggle.undosnapshot
    permission-message: You don't have permission to use that command.
    aliases: [undo, usnap]
  deleteallsnapshots:
    description: Deletes all snapshots.
    usage: /<command> CONFIRM
    permission: admintoggle.deleteallsnapshots
    permission-message: You don't have permission to use that command.
permissions:
  admintoggle.*:
    children:
      admintoggle.adminswitch: true
      admintoggle.newsnapshot: true
      admintoggle.loadsnapshot: true
      admintoggle.listsnapshots: true
      admintoggle.deletesnapshot: true
      admintoggle.savesnapshots: true
      admintoggle.admincheck: true
      admintoggle.undosnapshot: true
      admintoggle.deleteallsnapshots: true
      admintoggle.overwritesnapshot: true
      amdintoggle.listallsnapshots: true
  admintoggle.adminswitch:
    description: Allows use of the /adminswitch command.
  admintoggle.newsnapshot:
    description: Allows use of the /newsnapshot command.
  admintoggle.loadsnapshot:
    description: Allows use of the /loadsnapshot command.
  admintoggle.listsnapshots:
    description: Allows use of the /listsnapshots command.
  admintoggle.deletesnapshot:
    description: Allows use of the /deletesnapshot command.
  admintoggle.savesnapshots:
    description: Allows use of the /savesnapshots command.
  admintoggle.admincheck:
    description: Allows use of the /admincheck command.
  admintoggle.undosnapshot:
    description: Allows use of the /undosnapshot command.
  admintoggle.deleteallsnapshots:
    description: Allows use of the /deleteallsnapshots command.
  admintoggle.overwritesnapshot:
    description: Allows use of the /overwritesnapshot command.
  admintoggle.listallsnapshots:
    description: Allows use of the /listallsnapshots command.